#!/bin/bash

set -e

if [ -z "$1" ]; then
  BRANCH="fix-source-positions-for-inlines"
else
  BRANCH=$1
fi

echo "Using $BRANCH..."

echo "Checking out cmark-upstream"
echo "---------------------"
cd ext/commonmarker_fixed_sourcepos/cmark-upstream
git fetch origin
git checkout $BRANCH && git pull
sha=`git rev-parse HEAD`
cd ../../..
make
cp ext/commonmarker_fixed_sourcepos/cmark-upstream/extensions/*.{c,h} ext/commonmarker_fixed_sourcepos
cp ext/commonmarker_fixed_sourcepos/cmark-upstream/src/*.{inc,c,h} ext/commonmarker_fixed_sourcepos
rm ext/commonmarker_fixed_sourcepos/main.c
git add ext/commonmarker_fixed_sourcepos/cmark-upstream
git add ext/commonmarker_fixed_sourcepos/
git commit -m "Update cmark-upstream to $(git config submodule.ext/commonmarker/cmark-upstream.url | sed s_.git\$__)/commit/${sha}"
